apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
  labels:
    {{- include "recommendations.labels" . | nindent 4 }}
    app.kubernetes.io/component: recommendations
spec:
  replicas: {{ .Values.recommendation.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: recommendations
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recommendations
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: recommendations
          image: {{ .Values.recommendations.image }} 
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 5000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 5000
