name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          python -m pytest -v test/test.py -s
  deploy:
    name: Deploy to Okteto
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Okteto Deploy
        uses: okteto/pipeline@latest
        with:
          name: recommendations-service
          namespace: youryummy-maribelrb22
          variables: >-
            JWT_SECRET=${{ secrets.JWT_SECRET }}